# Generated by Django 3.2.6 on 2021-09-22 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('type_vacation', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Other', 'Other'), ('Paid Vacation', 'Paid Vacation')], default='Other', max_length=20)),
                ('date_vacation', models.DateTimeField(auto_now_add=True, verbose_name='vacation date')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='start vacation')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='end vacation')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['date_vacation'],
            },
        ),
    ]
