# Generated by Django 3.2.7 on 2021-09-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateTimeField(verbose_name='end vacation'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Employe'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateTimeField(verbose_name='start vacation'),
        ),
    ]
