# Generated by Django 3.2.6 on 2021-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_auto_20210923_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='type_vacation',
            field=models.CharField(choices=[('ANNUAL_LEAVE', 'Annual Leave'), ('SICK_LEAVE', 'Sick Leave'), ('OTHER', 'Other'), ('PAID_VACATION', 'Paid Vacation')], default='Other', max_length=20),
        ),
    ]
