# Generated by Django 3.2.6 on 2021-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_auto_20210923_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[(None, 'Choose vacation'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='type_vacation',
            field=models.CharField(choices=[(None, 'Choose vacation'), ('ANNUAL_LEAVE', 'Annual Leave'), ('SICK_LEAVE', 'Sick Leave'), ('OTHER', 'Other'), ('PAID_VACATION', 'Paid Vacation')], default='Other', max_length=20),
        ),
    ]
