# Generated by Django 3.2.6 on 2022-09-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0005_auto_20210925_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-date_vacation']},
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='type_vacation',
            field=models.CharField(choices=[('ANNUAL_LEAVE', 'Annual Leave'), ('SICK_LEAVE', 'Sick Leave'), ('PAID_VACATION', 'Paid Vacation'), ('OTHER', 'Other')], default='Other', max_length=20),
        ),
    ]
